name: .NET Core

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore src/MockQueryable/*.sln

      - name: Build
        run: dotnet build src/MockQueryable/*.sln --configuration Release --no-restore

      - name: Test with coverage
        run: |
          mkdir -p TestResults

          dotnet test src/MockQueryable/*.sln \
            --configuration Release \
            --no-build \
            /p:CollectCoverage=true \
            /p:CoverletOutput="$(pwd)/TestResults/coverage.opencover.xml" \
            /p:CoverletOutputFormat=opencover

          ls -R TestResults

      - name: Upload coverage results
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage
          path: TestResults
          if-no-files-found: error

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./TestResults/coverage.opencover.xml
          flags: unittests
          fail_ci_if_error: false
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
